/*
 * date_proc.c - remote procedures; called by server stub.
 */
#include <rpc/rpc.h>	/* standard RPC include file */
#include <time.h>
#include <sys/types.h>
#include <sys/sysinfo.h>
#include "date.h"	/* this file is generated by rpcgen */

#define MAX_LEN 100
/*
 * Return the binary date and time.
 */
char ** date_1(long *option)
{
    printf("here2\n");
    struct tm *timeptr; /* Pointer to time structure      */
    time_t clock;       /* Clock value (in secs)          */
    static char *ptr;   /* Return string                  */
    static char err[] = "Invalid Response \0";
    static char s[MAX_LEN];
    struct sysinfo mysys;
    static long CPUinfo;

    clock = time(0);
    timeptr = localtime(&clock);

    switch(*option)
        {
        case 1: strftime(s,MAX_LEN,"%A, %B %d, %Y",timeptr);
                ptr=s;
                break;

        case 2: strftime(s,MAX_LEN,"%T",timeptr);
                ptr=s;
                break;

        case 3: strftime(s,MAX_LEN,"%A, %B %d, %Y - %T",timeptr);
                ptr=s;
                break;
        case 4: sysinfo(&mysis);
                CPUinfo = mysys.loads[0];
                break;
        case 5:
                break;
        case 6:
                break;

        default: ptr=err;
                 break;
        }
    return(&ptr);
}
